name: Checkniner

on: [push]

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04]
        python: [3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt update
        sudo apt install -y libpq-dev
        pip install -r requirements.txt
    - name: Run CI script
      run: |
        scripts/cibuild
